server:
  port: 8080
spring:
  application:
    name: api-gateway
eureka:
  instance:
    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  cloud:
#    gateway:
#      routes:
#        - id: manga-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/manga/**
#            - Path=/genre/**
#        - id: authentication-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/auth/**